### ISSUE TITLE
Checks for existing plugins should use `name`

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-decorators#125]
These checks https://github.com/rwjblue/ember-decorators/blob/1547d8b7fb928c35b5253c864019384e4c65abe7/index.js#L53 and https://github.com/rwjblue/ember-decorators/blob/1547d8b7fb928c35b5253c864019384e4c65abe7/index.js#L57 should be augmented to look for `name` property on an instance as well as just the plain string value.

We should use something like:

```js
function hasPlugin(plugins, name, instance) {
  for (let plugin of plugins) { // ZOMG we can use let...of with node 4 :tada:
    if (typeof plugin === 'string') {
      if (plugin === name) { return true; }
      continue;
    } else if (Array.isArray(plugin)) {
      if (typeof plugin[0] === 'string')
        if (plugin[0] === name) { return true; }
        continue;
      } else {
        if (plugin[0] === instance) { return true; }
        continue;
      }
    }
  }
  
  return false;
}
```

Although there may be a much better way to write it that that (I just psudeo coded to show the various combos that I am aware of).

Specifically we need to support these scenarios before releasing:

```
// option 1
plugins: [
  'transform-decorators-legacy'
]

// option 2
plugins: [
  ['transform-decorators-legacy']
]

// option 3
plugins: [
  require('babel-plugin-transform-decorators-legacy').default
]
```

**Comment by pzuraq** [comment]
So dug into this a bit. I don't think we'll be able to support option 3 here because required babel plugins don't have any kind of identifier, and there's no way to compare instances:

![screen shot 2017-07-14 at 11 55 13 pm](https://user-images.githubusercontent.com/685518/28237259-136ead52-68f0-11e7-8b3b-00d5d6b7eb33.png)

This makes sense if you think about two potentially different packages being required in separate places and then compared (while I use the same package for the transform in this test app, it's `yarn link`ed so it requires it's own local version of the package). There's just no way for us to compare them, unless I'm missing some Node/Ember-CLI magic 😕 

Going to submit a fix for the other one, as well as for another bug I found (`this.parent` can exist, but confusingly it is either an Addon or a _Project_, not an App).

**Comment by pzuraq** [comment]
Also there is the escape option, `disableTransforms`, which users who must require the transforms manually can fall back on

**Comment by rwjblue** [comment]
Option 3 should be able to be checked _sometimes_ with a === check (since the function instances would be the same). It won't work if the node_modules structure ends up nesting the package in two locations (often times due to npm@2's poor dedupeing).
